config/routes.rb
Rails.application.routes.draw do
  resources :rounds do
    member do
      patch 'complete'
      patch 'open'
    end
  end
  resources :players, only: [:new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'rounds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :round

    validates :tag_in, presence: true
    validates :name, presence: true
end

app/models/round.rb
class Round < ApplicationRecord
    has_many :players
    after_initialize :init

    validates :name, presence: true

    def init
        self.complete ||= false
    end

    def complete_round
        tag_numbers = players.pluck(:tag_in).sort
        players.order(:score, :tag_in).each do |player|
            player.tag_out = tag_numbers.shift
            player.save!
        end
    end

    def open_round
        players.each do |player|
            player.tag_out = nil
            player.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ edit update destroy ]

  # GET /players/new
  def new
    @round_id = params[:round_id]
    @player = Player.new
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        round = Round.find(@player.round_id)
        format.html { redirect_to round, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /players/1/edit
  def edit
    @round_id = params[:round_id]
  end

  # PATCH/PUT /rounds/1 or /rounds/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        round = Round.find(@player.round_id)
        format.html { redirect_to round, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to round_url(@player.round_id), notice: "Player was successfully removed." }
      format.json { head :no_content }
    end
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :tag_in, :tag_out, :score, :round_id)
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: %i[ show edit update destroy complete open]

  # GET /rounds or /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1 or /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds or /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: "Round was successfully created." }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1 or /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: "Round was successfully updated." }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1 or /rounds/1.json
  def destroy
    Player.where(round_id: @round.id).destroy_all
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: "Round was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def complete
    @round.complete_round
    @round.complete = true
    @round.save!

    redirect_to @round, notice: "Round was completed."
  end

  def open
    @round.open_round
    @round.complete = false
    @round.save!

    redirect_to @round, notice: "Round was opened."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def round_params
      params.require(:round).permit(:id, :name, :complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EastboundTags</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <%= link_to "Eastbound Disc Golf Tags", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>

  <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div class="alert alert-danger" role="alert">
    <%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:

    <ul>
      <% player.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control mt-1", required: true %>
    <small id="nameHelp" class="form-text text-muted">Name of player.</small>
  </div>

  <div class="form-group  mt-3">
    <%= form.label :tag_in %>
    <%= form.text_field :tag_in, class: "form-control mt-1", required: true  %>
    <small id="nameHelp" class="form-text text-muted">Tag number the player is starting with. This will used to calculate final order in case of a tie.</small>
  </div>

  <div class="form-group  mt-3">
    <%= form.label :score %>
    <%= form.text_field :score, class: "form-control mt-1" %>
    <small id="nameHelp" class="form-text text-muted">Final score of the player. If you are creating a new player, feel free to leave this blank and edit the player after they are finished play.</small>
  </div>

  <%= form.hidden_field :round_id, value: @round_id %>

  <div class="actions mt-5">
    <%= form.submit "Submit", class: "btn btn-primary active" %>
  </div>
<% end %>
  

app/views/players/edit.html.erb
<h3>Editing <%= @player.name %></h3>

<%= render 'form', player: @player %>

<%= link_to 'Back', round_path(@player.round_id) %>

app/views/players/new.html.erb
<h3>New Player</h3>

<%= render 'form', player: @player %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/_form.html.erb
<%= form_with(model: round) do |form| %>
  <% if round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
        <% round.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <div class="field mt-3">
      <%= form.label :name, "Round Name" %>
      <%= form.text_field :name, class: "form-control mt-1", required: true %>
      <small id="nameHelp" class="form-text text-muted">This will be the name of the round you are about to play. Use something distinct so that it is easily referrable (something like a date and course).</small>
    </div>
  </div>

  <div class="actions mt-3">
    <%= form.submit 'Submit', class: "btn btn-primary " %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h3>Editing Round</h3>

<%= render 'form', round: @round %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h3>In Progress Rounds</h3>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.where(complete: false).order(created_at: :desc).each do |round| %>
      <tr>
        <td><strong><%= round.name %></strong></td>
        <td><%= round.created_at.strftime("%B %d, %Y") %></td>
        <td><%= link_to 'View', round %></td>
        <td><%= link_to 'Delete', round, method: :delete, data: { confirm: 'Are you sure? This is not a revertable action and will completely destroy the round.' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Round', new_round_path, {class: "btn btn-primary active"} %>

<div class="mt-5">
  <h3>Completed Rounds</h3>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Date</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rounds.where(complete: true).order(created_at: :desc).each do |round| %>
        <tr>
          <td><strong><%= round.name %></strong></td>
          <td><%= round.created_at %></td>
          <td><%= link_to 'View', round %></td>
          <td><%= link_to 'Delete', round, method: :delete, data: { confirm: 'Are you sure? This is not a revertable action and will completely destroy the round.' }%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rounds/new.html.erb
<h3>New Round</h3>

<%= render 'form', round: @round %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>


<h3><%= @round.name %> <%= link_to '(edit)', edit_round_path(@round), class: "h6 text-primary" %></h3>

<h6>This round <%= @round.complete ? "has been completed. Click \"Open Round\" to make changes." : "is currently in progress." %></h6>

<table class="table table-striped table-borderd">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Tag In</th>
      <th scope="col">Score</th>
      <th scope="col">Tag Out</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @round.players.order(:tag_out).each do |player| %>
      <tr>
        <td><strong><%= player.name %></strong></td>
        <td><%= player.tag_in %></td>
        <% if player.score %>
          <td><%= player.score %></td>
        <% else %>
          <td><span class="text-danger">Missing</span></td>
        <% end %>
        <td><%= player.tag_out %></td>
        
        <% if !@round.complete %>
         <td><%= link_to 'Edit', edit_player_path(player, round_id: @round.id) %></td>
          <td><%= link_to 'Remove', player, method: :delete, data: { confirm: 'Are you sure? This is not a revertable action and will completely removes the player.' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if !@round.complete %>
  <div>
    <%= link_to 'New Player', new_player_path(round_id: @round.id), class: "text-primary" %>
  </div>
<% end %>

<div class="mt-5">
  <% if !@round.complete %>
    <%= link_to "Complete Round", complete_round_path(@round), method: 'PATCH', class: "btn btn-primary active" %>
  <% else %>
    <%= link_to "Open Round", open_round_path(@round), method: 'PATCH', class: "btn btn-warning active" %>
  <% end %>
</div>

<div class="mt-3">
  <%= link_to 'Back', rounds_path %>
</div>